<?php
 return array(
   'APP_GROUP_LIST'=>'Home,Admin,Radmin,Sale',
   'DEFAULT_GROUP'=>'Home',
   'APP_GROUP_MODE'=>'1',
   'APP_GROUP_PATH'=>'Modules',
   'URL_MODEL'=>'2',
   'DB_HOST'=>'127.0.0.1',
   'DB_USER'=>'normal',
   'DB_PWD'=>'O1fpGg1eXENRCN7t',
   'DB_NAME'=>'viska',
   'DB_PREFIX'=>'',
   'URL_HTML_SUFFIX'=>'',
   'LOAD_EXT_CONFIG'=>'verify',
   'SHOW_PAGE_TRACE'=>'',
   'URL_CASE_INSENSITIVE'=>'1',
   'URL_ROUTER_ON'=>'1',
   'URL_ROUTE_RULES'=> array(
           '/^p_(\d+)_o_(\d+)$/'=>'Admin/Manage/apply?pid=:1&oid=:2',
   ),
   'TMPL_PARSE_STRING'=> array(
           '__SIGN__'=>'/signatures',
   ),
   'APP_TOKEN'=>'viskafudian',
   'APP_AESK'=>'',
   'YM_DOMAIN'=>'viska.weisika.net',
   'APP_ID'=>'wx4c9ffca0e1435398',
   'APP_SECRET'=>'a8249af4bff5b07f05c85ea540f08622',
   'SH_MB'=>'lxxxR_dDm7yVGC9ELMoKIz2RcPaMgi-sTJWINGjDfo8',
   'SQ_MB'=>'TRMqjYxiMf_su20kqlTrTzVyixSBdox7HrpdPEItK6g',
   'ORDER_MB'=> array(
           'NEW'=>'Em-M3owc7y7Z80B_ZNHBu6z1X9gk8tBj0_ttFBCXcLY',
           'CANCLE'=>'p9V_k9GpL4pUy0PR0AVT8byncm0P7fjuX5UxesAckrc',
           'AUDIT'=>'eJPBLm9-POMtaoYY2ay3ZzduQSr-2eDS3AbQxDXameQ',
   ),
   'MONEY_MB'=>'KHbGv4_kO16KhKacGNfQ6wUsMPYBo6VwkrDerE_kQC4',
   'UPGRADE_APPLY_MB'=>'yA-hOLURe7K6NJwmSKYscbj6AyJfvc3UldnzoLrQEUI',
   'UPGRADE_PASS_MB'=>'F6mPSWmbyfXzMgA-l_8nv-oN4JaQn-NSADb86UtBelY',
   'TAG_LEN'=>'50',
   'SYSTEM_NAME'=>'微斯咖新零售',
   'LEVEL_NUM'=>'4',
   'LEVEL_NAME'=> array(
           '1'=>'总代',
           '2'=>'省代',
           '3'=>'市代',
           '4'=>'特约',
   ),
   'LEVEL_NUM_MAX'=>'10',
   'GROW_MODEL'=>'1',
   'GROW_MODEL_LEVEL'=> array(
           '0'=>'',
           '1'=>'',
           '2'=>'',
           '3'=>'',
           '4'=>'',
   ),
   'IS_SUBMIT_ID_CARD_IMG'=>'0',
   'IS_TEST'=>'0',
   'AUDIT_WAY'=>'1',
   'AUDIT_WAY_LEVEL'=> array(
           '0'=>'',
           '1'=>'',
           '2'=>'',
           '3'=>'',
           '4'=>'',
   ),
   'ACTIVITY'=> array(
           'OPEN'=>'1',
           'WAY'=>'1',
           'OPEN_WXPAY'=>'1',
   ),
   'MONEY_COUNT_WAY'=>'0',
   'TEAM_REBATE_RATIO'=> array(
       'MONEY'=> array(
          '0'=>'10000',
          '1'=>'20000',
          '2'=>'50000',
          '3'=>'100000',
          '4'=>'200000',
          '5'=>'300000',
          '6'=>'500000',
              ),
       'RATIO'=> array(
          '0'=>'0.02',
          '1'=>'0.03',
          '2'=>'0.04',
          '3'=>'0.05',
          '4'=>'0.06',
          '5'=>'0.07',
          '6'=>'0.08',
              ),
   ),
   'PERSONAL_REBATE_RATIO'=> array(
       'MONEY'=> array(
          '0'=>'500000',
          '1'=>'500000',
          '2'=>'1000000',
          '3'=>'1500000',
          '4'=>'2500000',
          '5'=>'3000000',
              ),
       'RATIO'=> array(
          '0'=>'0.01',
          '1'=>'0.011',
          '2'=>'0.012',
          '3'=>'0.013',
          '4'=>'0.014',
          '5'=>'0.015',
              ),
   ),
   'DEFAULT_TEAM'=>'rec_path',
   'REBATE'=> array(
           'OPEN'=>'1',
           'ORDER'=>'1',
           'MONEY'=>'1',
           'ONCE'=>'1',
           'SAME_DEVELOPMENT'=>'1',
           'DEVELOPMENT'=>'1',
           'PERSONAL'=>'',
           'ORDINARY_TEAM'=>'1',
           'CLICK_TEAM_REBATE'=>'1',
   ),
   'FUNCTION_MODULE'=> array(
           'MONEY_APPLY_PAY_TYPE'=>'0',
           'TEAM'=>'1',
           'ORDER_FORMAT'=>'1',
           'MONEY'=>'0',
           'INTEGRAL_SHOP'=>'0',
           'MALL_SHOP'=>'0',
           'MARKET'=>'0',
           'GW'=>'0',
           'STOCK'=>'0',
           'BOSS_ORDER'=>'0',
           'STOCK_ORDER'=>'0',
           'LOAD_EXT_CONFIG'=>'extra',
   ),
   'SYSTEM_UPDATE'=>'git pull origin master-base',
   'LOG_RECORD'=>'',
   'MALL_REBATE'=> array(
           'OPEN'=>'',
           'ORDER'=>'',
   ),
   'MALL_REFUND'=> array(
           'IS_OPEN'=>'',
           'MALL_REFUND_PAY_TYPE'=>'0',
   ),
   'ORDER_SHIPPING'=>'1',
   'SHIPPING_REDUCE_WAY'=>'1',
   'IS_AUDITED'=>'1',
   'APP_TEST'=>'',
   'SEND_ORDER'=>'',
   'KDNIAO_ORDER'=>'',
   'BOSS'=> array(
           'PROVINCE'=>'',
           'CITY'=>'',
           'COUNTY'=>'',
           'DETAIL'=>'',
           'NAME'=>'',
           'PHONE'=>'',
   ),
   'kdnapi'=> array(
           'EBusinessID'=>'',
           'AppKey'=>'',
   ),
   'MESSAGE_MODULE'=> array(
           'OPEN'=>'0',
   ),

); ?>