<?php
 return array(
   'APP_GROUP_LIST'=>'Home,Admin,Radmin,Sale,Api',
   'DEFAULT_GROUP'=>'Home',
   'APP_GROUP_MODE'=>'1',
   'APP_GROUP_PATH'=>'Modules',
   'URL_MODEL'=>'2',
   'DB_HOST'=>'127.0.0.1',
   'DB_USER'=>'normal',
   'DB_PWD'=>'O1fpGg1eXENRCN7t',
   'DB_NAME'=>'',
   'DB_PREFIX'=>'',
   'URL_HTML_SUFFIX'=>'',
   'LOAD_EXT_CONFIG'=>'verify',
   'SHOW_PAGE_TRACE'=>'',
   'URL_CASE_INSENSITIVE'=>'1',
   'URL_ROUTER_ON'=>'1',
   'URL_ROUTE_RULES'=> array(
           '/^p_(\d+)_o_(\d+)$/'=>'Admin/Manage/apply?pid=:1&oid=:2',
   ),
   'TMPL_PARSE_STRING'=> array(
           '__SIGN__'=>'/signatures',
   ),
   'APP_TOKEN'=>'weisika',
   'APP_AESK'=>'',
   'YM_DOMAIN'=>'',
   'APP_ID'=>'',
   'APP_SECRET'=>'',
   'SH_MB'=>'',
   'SQ_MB'=>'',
   'ORDER_MB'=> array(
           'NEW'=>'',
           'CANCLE'=>'',
           'AUDIT'=>'',
   ),
   'MONEY_MB'=>'',
   'UPGRADE_MB'=>'',
   'TAG_LEN'=>'50',
   'SYSTEM_NAME'=>'',
   'LEVEL_NUM'=>'1',
   'LEVEL_NAME'=> array(
           '1'=>'总经销商',
   ),
   'LEVEL_NUM_MAX'=>'10',
   'GROW_MODEL'=>'3',
   'GROW_MODEL_LEVEL'=> array(
           '0'=>'1',
           '1'=>'3',
   ),
   'IS_SUBMIT_ID_CARD_IMG'=>'2',
   'IS_TEST'=>'0',
   'AUDIT_WAY'=>'1',
   'AUDIT_WAY_LEVEL'=> array(
           '0'=>'1',
   ),
   'ACTIVITY'=> array(
           'OPEN'=>'1',
           'WAY'=>'1',
           'OPEN_WXPAY'=>'1',
   ),
   'MONEY_COUNT_WAY'=>'0',
   'TEAM_REBATE_RATIO'=> array(
       'MONEY'=> array(
          '0'=>'10000',
          '1'=>'20000',
          '2'=>'50000',
          '3'=>'100000',
          '4'=>'200000',
          '5'=>'300000',
          '6'=>'500000',
              ),
       'RATIO'=> array(
          '0'=>'0.02',
          '1'=>'0.03',
          '2'=>'0.04',
          '3'=>'0.05',
          '4'=>'0.06',
          '5'=>'0.07',
          '6'=>'0.08',
              ),
   ),
   'PERSONAL_REBATE_RATIO'=> array(
       'MONEY'=> array(
          '0'=>'500000',
          '1'=>'500000',
          '2'=>'1000000',
          '3'=>'1500000',
          '4'=>'2500000',
          '5'=>'3000000',
              ),
       'RATIO'=> array(
          '0'=>'0.01',
          '1'=>'0.011',
          '2'=>'0.012',
          '3'=>'0.013',
          '4'=>'0.014',
          '5'=>'0.015',
              ),
   ),
   'DEFAULT_TEAM'=>'rec_path',
   'REBATE'=> array(
           'OPEN'=>'1',
           'ORDER'=>'1',
           'MONEY'=>'1',
           'ONCE'=>'1',
           'SAME_DEVELOPMENT'=>'1',
           'DEVELOPMENT'=>'1',
           'PERSONAL'=>'1',
           'ORDINARY_TEAM'=>'1',
           'CLICK_TEAM_REBATE'=>'0',
   ),
   'FUNCTION_MODULE'=> array(
           'MONEY'=>'1',
           'INTEGRAL_SHOP'=>'1',
           'MALL_SHOP'=>'1',
           'STOCK'=>'1',
           'MARKET'=>'1',
           'GW'=>'1',
           'TEAM'=>'1',
           'BOSS_ORDER'=>'1',
           'STOCK_ORDER'=>'0',
           'LOAD_EXT_CONFIG'=>'extra',
   ),
   'SYSTEM_UPDATE'=>'git pull',
   'LOG_RECORD'=>'',
   'MALL_REBATE'=> array(
           'OPEN'=>'',
           'ORDER'=>'',
   ),
   'MALL_REFUND'=> array(
           'IS_OPEN'=>'',
           'MALL_REFUND_PAY_TYPE'=>'0',
   ),
   'ORDER_SHIPPING'=>'1',
   'SHIPPING_REDUCE_WAY'=>'0',

); ?>
